/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev`/`next build`
// and should not be edited by hand once the toolchain has run. It's
// hand-written here only because Phase 1 was built without network
// access to install/run Next.js — see the Phase 1 report for details.
